### PR TITLE
updated 7zip version for windows only

### PR DESCRIPTION
**Pull request by VuruxCGM**
Hi, i updated the version of 7zip only for the windows version, because of the vulnerability issue of 7zip.

### CODE REVIEW

**Comment by develar** [comment]
Thanks! I will check on the weekend. Sorry, I cannot blindly accept PR without checking checksums of official binaries ;)

**Comment by VuruxCGM** [comment]
> Thanks! I will check on the weekend. Sorry, I cannot blindly accept PR without checking checksums of official binaries ;)

Thanks @develar !, are you planning to make a minor release or a patch?

**Comment by jpjcq** [comment]
Hi,
Any news on this ? Can you even replace these files with 23.01 version ? 

Thanks!

**Comment by kms0219kms** [comment]
@develar any updates?

**Comment by gorbinphilip** [comment]
@develar if not possible to do a release, can you add some info here to guide others where or how to get the binary for 7za.exe ?
While checking https://www.7-zip.org/download.html I could only find 7zr.exe

**Comment by gorbinphilip** [comment]
looks like the file is available on .7z archive (7-Zip Extra: standalone console version, 7z DLL, Plugin for Far Manager) [here](https://www.7-zip.org/download.html)

**Comment by mmaietta** [comment]
Closing in favor of https://github.com/develar/7zip-bin/pull/27

**Pull request closed without merging**
